name: xc7
channels:
  - litex-hub
dependencies:
  - litex-hub::symbiflow-yosys
  - litex-hub::symbiflow-yosys-plugins
  - litex-hub::symbiflow-vtr
  - gcc-riscv32-elf-nostdc
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
